spring:
  application:
    name: logbook
  config:
    # Import .env early so profiles and DB_* envs are available during bootstrap
    import: optional:file:.env[.properties]
  profiles:
    # Allow uppercase env key from .env to activate Spring profile
    active: ${SPRING_PROFILES_ACTIVE:}
  datasource:
    # Use file-based H2 for dev so data persists across restarts
    url: jdbc:h2:file:./data/logbook;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
